/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package initialPages;

import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author hasin
 */
public class DateTimeCostMgtForm extends javax.swing.JFrame {
    public String User = ""; 
    public String Patient = "";
    public String Date = "";
    public String Time = "";
    /**
     * Creates new form DateTimeCostMgtForm
     */
    public DateTimeCostMgtForm() {
        
    }

    DateTimeCostMgtForm(String user, String patient, String date, String time) {
        initComponents();
        User=user;
        Patient = patient;
        Date = date;
        Time = time;
        
        docNamelbl.setText("Doctor: "+User);
        patientNAmelbl.setText("Patient: "+Patient);
        datelbl.setText("Date: "+Date);
        timelbl.setText("Time: "+Time);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patientNAmelbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        docNamelbl = new javax.swing.JLabel();
        datelbl = new javax.swing.JLabel();
        timelbl = new javax.swing.JLabel();
        TotalCostlbl = new javax.swing.JLabel();
        changedatetimebtn = new javax.swing.JLabel();
        serveptntbtn = new javax.swing.JLabel();
        CostTxt = new javax.swing.JTextField();
        bckbtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        patientNAmelbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        patientNAmelbl.setText("Patient Name: ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Edit Record");

        docNamelbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        docNamelbl.setText("Doctor Name:");

        datelbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        datelbl.setText("Date:");

        timelbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        timelbl.setText("Time:");

        TotalCostlbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TotalCostlbl.setText("Total Cost:");

        changedatetimebtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        changedatetimebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        changedatetimebtn.setText("Change Date/Time");
        changedatetimebtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        changedatetimebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changedatetimebtnMouseClicked(evt);
            }
        });

        serveptntbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        serveptntbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        serveptntbtn.setText("Serve Patient");
        serveptntbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        serveptntbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                serveptntbtnMouseClicked(evt);
            }
        });

        CostTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CostTxtActionPerformed(evt);
            }
        });

        bckbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bckbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bckbtn.setText("Back");
        bckbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bckbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bckbtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TotalCostlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CostTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(timelbl, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(patientNAmelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(datelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(docNamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(236, 236, 236))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bckbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(348, 348, 348)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(changedatetimebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 460, Short.MAX_VALUE)
                .addComponent(serveptntbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(280, 280, 280))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bckbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(datelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(patientNAmelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 26, Short.MAX_VALUE))
                    .addComponent(docNamelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalCostlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CostTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changedatetimebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serveptntbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CostTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CostTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CostTxtActionPerformed

    private void changedatetimebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changedatetimebtnMouseClicked
        String newDate = JOptionPane.showInputDialog("Enter New Date", Date);
        String newTime= JOptionPane.showInputDialog("Enter New Time", Time);
        
        BufferedReader br = null;
        FileWriter fw = null;
        try {
            File rf = new File("AppointmentsData.txt");
            if (!rf.exists()) {
                System.out.println("Error");
            }
            br = new BufferedReader(new FileReader(rf));
            Object[] lines = br.lines().toArray();
            for (int i = 0; i < lines.length; i++) {
                String line = lines[i].toString().trim();
                String[] row = line.split(",");

                if (!(User.equals(row[2]) && Patient.equals(row[1]))) {
                    //write to new file
                    File file = new File("temp file.txt");
                    if (!file.exists()) {
                        file.createNewFile();
                        System.out.println("'temp file.txt' file createdLLLLL.");
                    }

                    fw = new FileWriter(file, true);
                    fw.write(row[0] + "," + row[1] + "," + row[2] + "," + row[3] + "," + row[4] + "\n");
                    fw.flush();
                    fw.close();
                } else {
                    //change and write to new file
                    File file = new File("temp file.txt");
                    if (!file.exists()) {
                        file.createNewFile();
                        System.out.println("'temp file.txt' file created.");
                    }
                    fw = new FileWriter(file, true);
                    fw.write(row[0] + "," + row[1] + "," + row[2] + "," + newDate + "," + newTime + "\n");
                    fw.flush();
                    fw.close();
                }
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Technical Error, call programmer");
        } finally {
            try {
                br.close();

            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Authentication Discarded. Technical Error, call programmer");;
            }
        }
        
        //rename new file and delete old file
        File f1 = new File("AppointmentsData.txt");
        File f2 = new File("temp file.txt");
        
        boolean b = f1.delete();
        Boolean x = f2.renameTo(f1);
        if(x && b){
            JOptionPane.showMessageDialog(this, "Date/Time changed successfully!");
        }else{
            JOptionPane.showMessageDialog(this, "Technical error, call programmer!");
        }
    }//GEN-LAST:event_changedatetimebtnMouseClicked

    private void serveptntbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serveptntbtnMouseClicked
        
        String cost = CostTxt.getText().toString();

        Boolean x = createPdf(Patient,Date,Time,cost);
        if(x == true){
            JOptionPane.showMessageDialog(this, "PDF generated successfully!");
        }else{
            JOptionPane.showMessageDialog(this, "Technical error, call programmer!");
        }
    }//GEN-LAST:event_serveptntbtnMouseClicked

    private void bckbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bckbtnMouseClicked
        PatientHandler ph = new PatientHandler();
        ph.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bckbtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DateTimeCostMgtForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DateTimeCostMgtForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DateTimeCostMgtForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DateTimeCostMgtForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DateTimeCostMgtForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CostTxt;
    private javax.swing.JLabel TotalCostlbl;
    private javax.swing.JLabel bckbtn;
    private javax.swing.JLabel changedatetimebtn;
    private javax.swing.JLabel datelbl;
    private javax.swing.JLabel docNamelbl;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel patientNAmelbl;
    private javax.swing.JLabel serveptntbtn;
    private javax.swing.JLabel timelbl;
    // End of variables declaration//GEN-END:variables

    public Boolean createPdf(String pname,String date,String time,String cost) {
        boolean x=false;
        try {
            Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream("patientInvoice.pdf"));
            document.open();
            document.add(new Paragraph("Patient name: "+pname+"\n"+"Cost: "+cost+"\n"+"Date: "+date+"\n"+"Time"+time+"\n"));
            document.close();
            x=true;
            System.out.println("the program has been executed");
        } catch (Exception e) {
            System.out.println(e.toString());
        }
        return x;
    }
}
