/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package initialPages;


import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author SUHA
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public SignupPage sup;
    public static String user = "lnone";
    public static String doctor= "";
    public static String mobile ="";
    
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        passwordLbl = new javax.swing.JLabel();
        usernameLbl = new javax.swing.JLabel();
        usernameTf = new javax.swing.JTextField();
        passwordTf = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        changeToSignup = new javax.swing.JLabel();
        backButtonLbl = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Page");
        setMaximumSize(new java.awt.Dimension(1200, 720));
        setMinimumSize(new java.awt.Dimension(1200, 720));
        setPreferredSize(new java.awt.Dimension(1200, 720));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(245, 243, 243));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("APU Medical Center");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 490, 90));

        jPanel1.setBackground(new java.awt.Color(1, 1, 1, 80));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(245, 246, 247));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sign In");

        passwordLbl.setFont(new java.awt.Font("Georgia", 1, 20)); // NOI18N
        passwordLbl.setForeground(new java.awt.Color(245, 243, 243));
        passwordLbl.setText("Password");
        passwordLbl.setMaximumSize(new java.awt.Dimension(95, 24));
        passwordLbl.setMinimumSize(new java.awt.Dimension(95, 24));
        passwordLbl.setPreferredSize(new java.awt.Dimension(95, 24));
        passwordLbl.setRequestFocusEnabled(false);

        usernameLbl.setFont(new java.awt.Font("Georgia", 1, 20)); // NOI18N
        usernameLbl.setForeground(new java.awt.Color(245, 243, 243));
        usernameLbl.setText("Username");
        usernameLbl.setMaximumSize(new java.awt.Dimension(95, 24));
        usernameLbl.setMinimumSize(new java.awt.Dimension(95, 24));
        usernameLbl.setPreferredSize(new java.awt.Dimension(95, 24));
        usernameLbl.setRequestFocusEnabled(false);

        usernameTf.setBackground(new java.awt.Color(222, 229, 254));
        usernameTf.setFont(new java.awt.Font("Roboto", 2, 20)); // NOI18N
        usernameTf.setForeground(new java.awt.Color(100, 100, 100));
        usernameTf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        usernameTf.setMargin(new java.awt.Insets(0, 10, 0, 10));

        passwordTf.setBackground(new java.awt.Color(222, 229, 254));
        passwordTf.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        passwordTf.setForeground(new java.awt.Color(100, 100, 100));
        passwordTf.setMargin(new java.awt.Insets(0, 10, 0, 10));

        loginBtn.setBackground(new java.awt.Color(177, 196, 208));
        loginBtn.setFont(new java.awt.Font("Georgia", 2, 24)); // NOI18N
        loginBtn.setText("Login");
        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        changeToSignup.setFont(new java.awt.Font("Georgia", 3, 15)); // NOI18N
        changeToSignup.setForeground(new java.awt.Color(245, 243, 243));
        changeToSignup.setText("Don't Have Account? Sign Up Now!");
        changeToSignup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changeToSignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeToSignupMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passwordLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(usernameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(passwordTf, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(usernameTf))
                .addGap(101, 101, 101))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(changeToSignup)))
                .addContainerGap(223, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usernameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passwordTf, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(loginBtn)
                .addGap(31, 31, 31)
                .addComponent(changeToSignup)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 700, 330));

        backButtonLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backButtonLbl.setText("Back");
        backButtonLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonLblMouseClicked(evt);
            }
        });
        backButtonLbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonLblActionPerformed(evt);
            }
        });
        getContentPane().add(backButtonLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 70, 30));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_images/login_bg.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
//    My custom methods
    public String requestedUser(){
        String user = "";
        BufferedReader br = null;
        try {
            File rf = new File("PresentUsr.txt");
            if(!rf.exists()){
                rf.createNewFile();
                System.out.println("'PresentUsr.txt' file created.");
            }
            br = new BufferedReader(new FileReader(rf));
            user = br.lines().toArray()[0].toString();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Cant find requested user");
        }
        finally{
            try {
                br.close();
            } catch (IOException ex) {
                Logger.getLogger(SignupPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return user;
    }
    
    private void changeToSignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeToSignupMouseClicked
        // TODO add your handling code here:
        sup = new SignupPage(this,true);
        sup.setVisible(true);
    }//GEN-LAST:event_changeToSignupMouseClicked

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        String usrname = this.usernameTf.getText();
        doctor= this.usernameTf.getText();
        String password = this.passwordTf.getText();
        String rusr = requestedUser();
        boolean isauth = false;
        
        BufferedReader br = null;
        try {
            File rf = new File("AuthData.txt");
            if(!rf.exists()){
                rf.createNewFile();
                System.out.println("'AuthData.txt' file created.");
            }
            br = new BufferedReader(new FileReader(rf));
            Object[] lines = br.lines().toArray();
            for(int i=0; i < lines.length; i++){
                String line = lines[i].toString().trim();
                String[] row = line.split(",");
                
                if(usrname.equals(row[1]) && password.equals(row[4])){
                    
                    File file= new File("LoginReference.txt");
                    if(!file.exists()){
                        file.createNewFile();
                        System.out.println("'LoginReference.txt' file created.");
                    }else{
                        boolean x=file.delete();
                        if(x==true){
                            file.createNewFile();
                        }
                    }
                    
                    FileWriter fw = new FileWriter(file, true);
                    fw.write(usrname+","+password+"\n");
                    fw.close();
                    mobile=row[3];
                    isauth = true;
                    this.user = row[5];
                }
            }
            if (isauth){
                if ("admin".equals(this.user) && rusr.equals(this.user)) {
                    //saving username reference
                    
                    AdminPage ap = new AdminPage();
                    ap.setVisible(true);
                    this.dispose();
                }
                else if ("doctor".equals(this.user) && rusr.equals(this.user)){
                    //JOptionPane.showMessageDialog(this, "Logged in as Doctor! ");
                    
                    DoctorPage dp = new DoctorPage();
                    dp.setVisible(true);
                    this.dispose();
                }
                else{
                    System.out.println(this.user+" -- "+ rusr);
                    JOptionPane.showMessageDialog(this, "You are not " + rusr.toUpperCase());
                }
            }
            else
                JOptionPane.showMessageDialog(this, "Authentication Discarded. Invalid Input");
            
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Authentication Discarded. Technical Error");
        }finally{
            try {
                br.close();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Authentication Discarded. Technical Error");;
            }
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void backButtonLblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonLblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonLblActionPerformed

    private void backButtonLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonLblMouseClicked
        WelcomePage wPage= new WelcomePage();
        wPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonLblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButtonLbl;
    private javax.swing.JLabel changeToSignup;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JPasswordField passwordTf;
    private javax.swing.JLabel usernameLbl;
    private javax.swing.JTextField usernameTf;
    // End of variables declaration//GEN-END:variables
}
